export interface StaticContent { title: string; description: string; sections: Array<{ heading: string; body: string[] }> }
export const staticContent: Record<string, StaticContent> = {
  about: { title: 'About Face Shape Lab', description: 'AI-powered facial analysis for styling, grooming, eyewear, and self-education.', sections: [{ heading: 'What we do', body: ['Face Shape Lab analyzes uploaded face photos and returns face shape, symmetry, age, eye, lip, and nose insights using the same live API as the web app.', 'The app focuses on practical recommendations for grooming, hair, eyewear, makeup, and style decisions.'] }, { heading: 'Important note', body: ['Results are automated estimates for personal guidance. They are not medical advice, identity verification, or a substitute for professional consultation.'] }] },
  contact: { title: 'Contact Us', description: 'Questions, support requests, or partnership inquiries.', sections: [{ heading: 'Support', body: ['Use the website contact channel or your support inbox to ask about scans, billing, product data, or privacy concerns.', 'When reporting a bug, include your device, app version, and the screen where the issue happened.'] }] },
  privacy: { title: 'Privacy Policy', description: 'How image and account workflows are handled inside the app.', sections: [{ heading: 'Images', body: ['Images are sent to the configured live API only when you choose to scan, check reuse, or generate a style edit.', 'Use the privacy image reuse tool to check internal matches where supported by the backend.'] }, { heading: 'Account data', body: ['Auth tokens are stored with expo-secure-store. Logout clears local secure tokens and cached user state.'] }] },
  disclaimer: { title: 'Disclaimer', description: 'Understand the limitations before using AI facial analysis.', sections: [{ heading: 'Automated estimates', body: ['The analysis may vary with lighting, pose, blur, camera angle, occlusion, and image quality.', 'Do not use the app for medical diagnosis, identity verification, legal decisions, or high-stakes judgments.'] }] },
  faqs: { title: 'FAQs', description: 'Common questions about scans, accuracy, privacy, and reports.', sections: [{ heading: 'How accurate is it?', body: ['Accuracy depends on a clear, front-facing photo and good lighting. The API returns confidence and quality warnings so users understand reliability.'] }, { heading: 'Can I save scans?', body: ['Signed-in users can view scan history, save favorites, compare scans, and open report details.'] }, { heading: 'Which tools are included?', body: ['Face shape, symmetry, age, eye shape, lip shape, nose shape, image reuse, style edit, dashboard, favorites, billing status, and admin views where authorized.'] }] },
  pricing: { title: 'Pricing', description: 'Plans mirror the backend subscription workflow.', sections: [{ heading: 'Free', body: ['Basic scans and core recommendations for personal use.'] }, { heading: 'Pro', body: ['More saved history, favorites, style workflows, and advanced report workflows depending on backend configuration.'] }, { heading: 'Business', body: ['Team and admin-focused workflows for product, report, and analytics management.'] }] },
};
