import { useMutation } from '@tanstack/react-query';
import { Image } from 'expo-image';
import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { ProtectedRoute } from '@/components/ui/ProtectedRoute';
import { ScreenWrapper } from '@/components/ui/ScreenWrapper';
import { ImagePickerPanel } from '@/features/detectors/ImagePickerPanel';
import { facefitApi } from '@/services/facefitApi';
import { useAppTheme } from '@/hooks/useAppTheme';
import { useToast } from '@/hooks/useToast';
import type { ApiError } from '@/services/apiClient';
import type { StyleEditRegion } from '@/types/api';
import type { ImageAsset } from '@/utils/formData';
const regions: StyleEditRegion[] = ['hair', 'glasses', 'beard', 'lips', 'nose'];
export function StyleEditScreen() { const theme = useAppTheme(); const { showToast } = useToast(); const [asset, setAsset] = useState<ImageAsset | null>(null); const [region, setRegion] = useState<StyleEditRegion>('hair'); const [instruction, setInstruction] = useState('Make the selected style natural and photorealistic.'); const mutation = useMutation({ mutationFn: () => facefitApi.generateStyleEdit({ asset: asset as ImageAsset, region, instruction }), onError: (e: ApiError) => showToast(e.message) }); const imageUri = mutation.data ? `data:${mutation.data.mime_type};base64,${mutation.data.image_base64}` : asset?.uri; return <ProtectedRoute><ScreenWrapper><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: theme.text }]}>Style template studio</Text><ImagePickerPanel title="Upload style source" disabled={mutation.isPending} onPick={setAsset} />{imageUri ? <Image source={{ uri: imageUri }} style={styles.preview} contentFit="cover" /> : null}<Card><Text style={[styles.cardTitle, { color: theme.text }]}>Region</Text><View style={styles.regions}>{regions.map((item) => <Button key={item} size="sm" title={item} variant={item === region ? 'primary' : 'secondary'} onPress={() => setRegion(item)} />)}</View><Input multiline placeholder="Instruction" value={instruction} onChangeText={setInstruction} /><Button disabled={!asset || mutation.isPending} title="Generate edit" onPress={() => mutation.mutate()} /></Card>{mutation.isPending ? <LoadingSpinner label="Generating edit" /> : null}</ScrollView></ScreenWrapper></ProtectedRoute>; }
const styles = StyleSheet.create({ content: { padding: 18, gap: 16, paddingBottom: 40 }, title: { fontSize: 28, fontWeight: '900' }, preview: { width: '100%', height: 260, borderRadius: 24 }, cardTitle: { fontWeight: '900', marginBottom: 10 }, regions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 } });
