export const strings = {
  appName: 'Face Shape Lab',
  brandTagline: 'AI face shape, symmetry, age, eye, lip, and nose analysis.',
  uploadHelper: 'Upload a clear, front-facing selfie. JPEG, PNG, or WebP works best.',
  uploadSelfie: 'Upload selfie',
  cameraImage: 'Camera image',
  faceAnalysisScan: 'Face analysis scan',
  imageTooLarge: 'Image is too large. Please choose an image under 12 MB.',
  cameraPermission: 'Camera permission is required to capture a face scan.',
  galleryPermission: 'Photo library permission is required to choose an image.',
  cameraUnavailable: 'The camera could not be opened. Use a physical phone with a camera or upload a photo instead.',
  cameraSimulatorUnavailable: 'The iOS Simulator has no camera. Open this project on a physical iPhone to take a photo, or upload one here.',
  galleryUnavailable: 'The photo library could not be opened. Please try again.',
  genericError: 'Something went wrong. Please try again.',
  offlineError: 'Network unavailable. Check your internet connection and try again.',
  loginTitle: 'Welcome back',
  signupTitle: 'Create account',
  forgotTitle: 'Reset password',
  authSubtitle: 'Use your account to save reports, favorites, and scan history.',
  forgotSubtitle: 'Enter your email and we will request a reset link.',
  namePlaceholder: 'Name',
  emailPlaceholder: 'Email',
  passwordPlaceholder: 'Password',
  loginAction: 'Log In',
  signupAction: 'Create Account',
  forgotAction: 'Send Reset Link',
  forgotLink: 'Forgot password?',
  signupLink: "Don't have an account? Sign up",
  loginLink: 'Already have an account? Login',
  protectedMessage: 'Please sign in to continue.',
  noHistory: 'No scans yet. Run your first analysis from the Scan tab.',
  noFavorites: 'No favorites saved yet.',
  noAdminData: 'Admin data will appear here when available.',
  analysisEmpty: 'Pick or capture an image to start the scan.',
  scanSaved: 'Scan saved to favorites.',
  reportUnavailable: 'This scan does not have a downloadable report yet.',
  deepLinkHost: 'faceshapapp://',
} as const;
