export const strings = {
  appName: 'Face Shape Lab',
  brandTagline: 'AI face and style insights.',
  uploadHelper: 'Use a clear front-facing selfie.',
  uploadSelfie: 'Upload selfie',
  cameraImage: 'Take photo',
  faceAnalysisScan: 'Face scan',
  imageTooLarge: 'Choose an image under 12 MB.',
  cameraPermission: 'Allow camera access to continue.',
  galleryPermission: 'Allow photo access to continue.',
  cameraUnavailable: 'Camera unavailable. Upload a photo instead.',
  cameraSimulatorUnavailable: 'The iOS Simulator has no camera. Open this project on a physical iPhone to take a photo, or upload one here.',
  galleryUnavailable: 'Photos unavailable. Try again.',
  genericError: 'Something went wrong. Try again.',
  offlineError: 'You are offline. Try again.',
  loginTitle: 'Welcome back',
  signupTitle: 'Create account',
  forgotTitle: 'Reset password',
  authSubtitle: 'Save scans and favorites.',
  forgotSubtitle: 'Enter your email.',
  namePlaceholder: 'Name',
  emailPlaceholder: 'Email',
  passwordPlaceholder: 'Password',
  loginAction: 'Log In',
  signupAction: 'Create Account',
  forgotAction: 'Send Reset Link',
  forgotLink: 'Forgot password?',
  signupLink: "Don't have an account? Sign up",
  loginLink: 'Already have an account? Login',
  protectedMessage: 'Sign in to continue.',
  noHistory: 'Your scans will appear here.',
  noFavorites: 'No favorites yet.',
  noAdminData: 'No data yet.',
  analysisEmpty: 'Upload a selfie to start.',
  scanSaved: 'Scan saved to favorites.',
  reportUnavailable: 'Report not ready.',
  reportExportReady: 'Report export is ready.',
  reportExportFailed: 'Export failed. Try again.',
  deepLinkHost: 'faceshapapp://',
} as const;
